name: shopping-list-dev

networks:
  shopping-list-dev:

volumes:
  postgres-data:
  seq-data:

services:
  postgres:
    image: postgres:17
    container_name: shopping-list-dev.postgres
    networks:
      - shopping-list-dev
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgrespw}
    restart: unless-stopped

  seq:
    image: datalust/seq:2024.3
    container_name: shopping-list-dev.seq
    networks:
      - shopping-list-dev
    ports:
      - "5341:80"
    volumes:
      - seq-data:/data
    environment:
      ACCEPT_EULA: Y
    restart: unless-stopped
